---
claude_code_enabled: true
claude_code_settings_enabled: true
claude_code_skills_enabled: true

claude_code_skills:
  - source: "github/awesome-copilot"
    skills:
      - chrome-devtools
      - gh-cli
      - prd
      - git-commit
  - source: "vercel-labs/skills"
    skills:
      - find-skills
